function [point_array,point_number] = point_generation_cube(L, line_number);

point_x = L*[linspace(-0.5,0.5,line_number) linspace(-0.5,0.5,line_number) linspace(-0.5,0.5,line_number) linspace(-0.5,0.5,line_number) ...
                    0.5*ones(1, line_number) 0.5*ones(1, line_number) 0.5*ones(1, line_number) 0.5*ones(1, line_number) ...
                   -.5*ones(1, line_number) -.5*ones(1, line_number) -.5*ones(1, line_number) -.5*ones(1, line_number)];
point_y = L*[0.5*ones(1, line_number) 0.5*ones(1, line_number) -.5*ones(1, line_number) -.5*ones(1, line_number) ...
                    linspace(-0.5,0.5,line_number) linspace(-0.5,0.5,line_number) 0.5*ones(1, line_number) -.5*ones(1, line_number) ...
                    linspace(-0.5,0.5,line_number) linspace(-0.5,0.5,line_number) 0.5*ones(1, line_number) -.5*ones(1, line_number)];
point_z = L*[0.5*ones(1, line_number) -.5*ones(1, line_number) 0.5*ones(1, line_number) -.5*ones(1, line_number) ...
                    0.5*ones(1, line_number) -.5*ones(1, line_number) linspace(-0.5,0.5,line_number) linspace(-0.5,0.5,line_number) ...
                    0.5*ones(1, line_number) -.5*ones(1, line_number) linspace(-0.5,0.5,line_number) linspace(-0.5,0.5,line_number)];
point_array = [point_x;point_y;point_z];
point_number = line_number*12;